### ISSUE TITLE
Traceback on examples/auth when go to /admin

### ISSUE THREAD

**Issue by skyline42sh** [flask-admin/flask-admin#1081]
Hello,

We have a traceback when we go to the admin page after lauching the python example/auth/app.py

Thanks,
Skyline

---

 * Running on http://192.168.2.236:5000/ (Press CTRL+C to quit)
 * Restarting with stat
192.168.2.1 - - [13/Oct/2015 07:17:48] "GET / HTTP/1.1" 200 -
192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/ HTTP/1.1" 500 -
Traceback (most recent call last):

File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/base.py", line 443, in index
    return self.render(self._template)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/base.py", line 299, in render
    return render_template(template, **kwargs)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
File "/root/flask-admin/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
File "/root/flask-admin/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
File "/root/flask-admin/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
File "/root/flask-admin/examples/auth/templates/admin/index.html", line 1, in top-level template code
    {% extends 'admin/master.html' %}
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
File "/root/flask-admin/examples/auth/templates/my_master.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 30, in top-level template code
    {% block page_body %}
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 47, in block "page_body"
    {% block main_menu %}
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 49, in block "main_menu"
    {{ layout.menu() }}
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/layout.html", line 46, in template
    {%- if item.is_accessible() and item.is_visible() -%}
File "/root/flask-admin/env/lib/python2.7/site-packages/flask_admin/menu.py", line 120, in is_accessible
    return self._view.is_accessible()
File "/root/flask-admin/examples/auth/app.py", line 59, in is_accessible
    if not current_user.is_active() or not current_user.is_authenticated():
TypeError: 'bool' object is not callable

192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -

192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -

192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -

192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -

192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

192.168.2.1 - - [13/Oct/2015 07:17:50] "GET /admin/?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -

**Comment by pawl** [comment]
Looks like this is due to some recent changes in flask-login: https://github.com/maxcountryman/flask-login/pull/177
