### ISSUE TITLE
override templates: backend looks broken

### ISSUE THREAD

**Issue by mankoell** [flask-admin/flask-admin#1169]
Copied `base.html` into my own `templates/admin` folder. The whole flask backend got broken now.

![bildschirmfoto vom 2016-01-10 14 18 47](https://cloud.githubusercontent.com/assets/1057526/12221673/5cae7f22-b7a5-11e5-946a-3cbb08bcc50f.png)

No icons, inline editing no longer works:
![bildschirmfoto vom 2016-01-10 14 19 22](https://cloud.githubusercontent.com/assets/1057526/12221675/60a43d56-b7a5-11e5-886c-c72cd3acb051.png)

When I copy the whole `templates/admin` to my own templates folder, trying to access my model page:

```
jinja2.exceptions.UndefinedError
UndefinedError: 'list_forms' is undefined

Traceback (most recent call last)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
return self._run_view(f, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
return fn(self, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/flask_admin/model/base.py", line 1814, in index_view
return_url=self._get_list_url(view_args),
File "/usr/local/lib/python2.7/site-packages/flask_admin/base.py", line 307, in render
return render_template(template, **kwargs)
File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
context, ctx.app)
File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
rv = template.render(context)
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/bullock/wwii/templates/admin/model/list.html", line 5, in top-level template code
{% import 'admin/actions.html' as actionlib with context %}
File "/bullock/wwii/templates/admin/master.html", line 1, in top-level template code
{% extends admin_base_template %}
File "/bullock/wwii/templates/admin/base.html", line 25, in top-level template code
{% block page_body %}
File "/bullock/wwii/templates/admin/base.html", line 69, in block "page_body"
{% block body %}{% endblock %}
File "/bullock/wwii/templates/admin/model/list.html", line 62, in block "body"
{% block model_list_table %}
File "/bullock/wwii/templates/admin/model/list.html", line 110, in block "model_list_table"
{% block list_row scoped %}
File "/bullock/wwii/templates/admin/model/list.html", line 160, in block "list_row"
Open an interactive python shell in this frame{% set form = list_forms[get_pk_value(row)] %}
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 389, in getitem
return obj[argument]
UndefinedError: 'list_forms' is undefined
```

> To override any of the built-in templates, simply copy them from the Flask-Admin source into your 
> project’s templates/admin/ directory. As long as the filenames stay the same, the templates in your 
> project directory should automatically take precedence over the built-in ones.

:hankey: :hankey: :hankey:

**Comment by pafmaf** [comment]
@mankoell What version / commit are you referring to? How do you init?

**Comment by pawl** [comment]
It sounds like your list.html is from the master branch, but you have the 1.4 release installed.

@mankoell You should be able to fix this by using this command to install the most recent code from the master branch: `pip install -e git+https://github.com/flask-admin/flask-admin.git@master#egg=flask-admin`

This section of the docs has more info: http://flask-admin.readthedocs.org/en/latest/introduction/#working-with-the-built-in-templates
> Rather than overriding the built-in templates completely, it’s best to extend them. This will make it simpler for you to upgrade to new Flask-Admin versions in future.

**Comment by mankoell** [comment]
@pafmaf python 2.7 with current version from pip

@pawl I thought pip already has the latest version, why should it work with?

I can't extend layouts as there is no way/block to change the navbar how I want it to be.

**Comment by pawl** [comment]
The change that added `list_forms` to the template was made only a week ago and hasn't made it into another release yet.

You can still extend list.html and override the block that has the actions navbar. But, again, it's not good idea to copying the entire list.html and override more than what's necessary. 

Here's the list.html from the 1.4 release: https://github.com/flask-admin/flask-admin/blob/v1.4.0/flask_admin/templates/bootstrap3/admin/model/list.html
