### ISSUE TITLE
Flask admin peewee example failed to run with 2.8 version

### ISSUE THREAD

**Issue by gerosalesc** [flask-admin/flask-admin#1185]
I tried the Peewee integration [example](https://github.com/flask-admin/flask-admin/blob/master/examples/peewee/app.py) as plain as Copy pasting it and I am getting this error:

```
MY_ENV_PATH/bin/python "MY_PROJECT/bgadmin/app.py"
Traceback (most recent call last):
  File "MY_PROJECT/bgadmin/app.py", line 88, in <module>
    admin.add_view(UserAdmin(User))
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 170, in __init__
    menu_icon_value=menu_icon_value)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 718, in __init__
    self._refresh_cache()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 810, in _refresh_cache
    self._refresh_forms_cache()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 735, in _refresh_forms_cache
    self._create_form_class = self.get_create_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1147, in get_create_form
    return self.get_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1100, in get_form
    return self.scaffold_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 264, in scaffold_form
    form_class = self.scaffold_inline_form_models(form_class)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 297, in scaffold_inline_form_models
    m)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/form.py", line 213, in contribute
    for field in info.model._meta.get_fields():
AttributeError: 'ModelOptions' object has no attribute 'get_fields'
```
The version of the libraries are: Flask 0.10.1, Flask-Admin 1.4.0, peewee 2.8.0

Thanks in advance

**Comment by gerosalesc** [comment]
This problem may seem the same described in #1117 that was solved in #1125 but I am still getting this error. I downgraded Peewee to 2.7.4 but still persisted. Any help will be appreciated, thanks in advance.

**Comment by kdart** [comment]
Me too, using peewee 2.8.0. The joys of living on the bleeding edge. :)

**Comment by kdart** [comment]
Thanks for fast response. It's very helpful.
