### ISSUE TITLE
flask_admin   'get_url' is undefined

### ISSUE THREAD

**Issue by timgogochen** [flask-admin/flask-admin#1228]
Hi supporter,

When I use flask-admin ,get error info like this ##
jinja2.exceptions.UndefinedError
UndefinedError: 'get_url' is undefined

Traceback (most recent call last)
File "C:\Python274\lib\site-packages\flask\app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python274\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python274\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python274\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python274\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python274\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python274\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python274\lib\site-packages\flask\app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Python274\lib\site-packages\flask_admin\base.py", line 68, in inner
return self._run_view(f, *args, **kwargs)
File "C:\Python274\lib\site-packages\flask_admin\base.py", line 367, in _run_view
return fn(self, *args, **kwargs)
File "C:\Python274\lib\site-packages\flask_admin\model\base.py", line 1814, in index_view
return_url=self._get_list_url(view_args),
File "C:\python_source\quokka\quokka\core\admin\models.py", line 43, in render
return render_template(template, theme=theme, **kwargs)
File "C:\python_source\quokka\quokka\core\templates.py", line 16, in render_template
return render_theme_template(theme, template, **context)
File "C:\Python274\lib\site-packages\quokka_themes\__init__.py", line 191, in render_theme_template
return render_template(last, **context)
File "C:\Python274\lib\site-packages\flask\templating.py", line 128, in render_template
context, ctx.app)
File "C:\Python274\lib\site-packages\flask\templating.py", line 110, in _render
rv = template.render(context)
File "C:\Python274\lib\site-packages\jinja2\environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "C:\Python274\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\model\list.html", line 5, in top-level template code
{% import 'admin/actions.html' as actionlib with context %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\master.html", line 1, in top-level template code
{% extends admin_base_template %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 30, in top-level template code
{% block page_body %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 59, in block "page_body"
{% block body %}{% endblock %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\model\list.html", line 13, in block "body"
{% block model_menu_bar %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\model\list.html", line 24, in block "model_menu_bar"
<a href="{{ get_url('.create_view', url=return_url) }}" title="{{ _gettext('Create New Record') }}">{{ _gettext('Create') }}</a>
UndefinedError: 'get_url' is undefined

How can I solve this issue?
Thanks and Best Regards

**Comment by mrjoes** [comment]
Quokka related. Seems like it is not passing full Flask-Admin context to render function. Check with Quokka devs.

**Comment by pawl** [comment]
Like mrjoes said, "not passing full Flask-Admin context to render function". This usually happens when you use render_template on a flask-admin template instead of self.render.

**Comment by MrLeeh** [comment]
I get the same issue when trying your [auth example](https://github.com/flask-admin/flask-admin/tree/master/examples/auth).

Using:
* Flask 0.10.1
* Flask-Admin 1.4.2
* Flask-Security 1.7.5

```
    Traceback (most recent call last):
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\_compat.py", line 33, in reraise
        raise value
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\_compat.py", line 33, in reraise
        raise value
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_security\decorators.py", line 225, in wrapper
        return f(*args, **kwargs)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_security\views.py", line 87, in login
        **_ctx('login'))
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_security\core.py", line 447, in render_template
        return render_template(*args, **kwargs)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\templating.py", line 128, in render_template
        context, ctx.app)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask\templating.py", line 110, in _render
        rv = template.render(context)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\jinja2\environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\jinja2\_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\templates\security\login_user.html", line 3, in top-level template code
        {% include "security/_messages.html" %}
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_admin\templates\bootstrap2\admin\master.html", line 1, in top-level template code
        {% extends admin_base_template %}
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\templates\my_master.html", line 1, in top-level template code
        {% extends 'admin/base.html' %}
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 14, in top-level template code
        {% block head_css %}
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 15, in block "head_css"
        <link href="{{ admin_static.url(filename='bootstrap/bootstrap2/css/bootstrap.css', v='2.3.2') }}" rel="stylesheet">
      File "C:\Users\Lehmann\data\python\experimental\packages\flask-admin\examples\auth\venv_win\lib\site-packages\flask_admin\templates\bootstrap2\admin\static.html", line 2, in template
        {{ get_url('admin.static', *varargs, **kwargs) }}
    jinja2.exceptions.UndefinedError: 'get_url' is undefined
```

**Comment by mrjoes** [comment]
I corrected example. Try it now.

**Comment by MrLeeh** [comment]
Now it works

**Comment by edouardberthe** [comment]
Hello,
I have the same problem, but I don't use Quokka at all.
Here are my requirements:

    alembic==0.8.7
    Babel==2.3.4
    blinker==1.4
    click==6.6
    Flask==0.11.1
    Flask-Admin==1.4.2
    Flask-BabelEx==0.9.3
    Flask-DebugToolbar==0.10.0
    Flask-Login==0.3.2
    Flask-Mail==0.9.1
    Flask-Migrate==1.8.1
    Flask-Principal==0.4.0
    Flask-Script==2.0.5
    Flask-Security==1.7.5
    Flask-SQLAlchemy==2.1
    Flask-WTF==0.12
    gunicorn==19.6.0
    itsdangerous==0.24
    Jinja2==2.8
    Mako==1.0.4
    MarkupSafe==0.23
    passlib==1.6.5
    psycopg2==2.6.2
    python-editor==1.0.1
    pytz==2016.6.1
    speaklater==1.3
    SQLAlchemy==1.0.14
    Werkzeug==0.11.10
    WTForms==2.1

Can you explain the process you did to solve the problem in your auth example, so as we could correct ours too?

Thanks

**Comment by vlasy** [comment]
I had the same problem so for anyone solving this (I will describe my case)
- problem is caused by [this change in newer versions of flask-admin](https://github.com/flask-admin/flask-admin/commit/282c7c516f3fbb25720f24c158d4d77400b4303e) and some template context conflicts (for me it was probably flask-admin and flask-security)
- **mrjoes** is probably refering to [this change](https://github.com/flask-admin/flask-admin/commit/6a06ae064cac3020c10a41ea41b946c386303a9b) and that is also what worked for me - i used the same snippet and instead of security context processor set it as global context processor after application and admin initilization

```
@application.app.context_processor
def inject_url():
    return dict(
         # admin_base_template=admin.base_template,
         admin_view=admin.index_view,
         # h=admin_helpers,
         get_url=url_for
     )
```

**Comment by kontur** [comment]
Found this when searching from #1858 — @vlasy 's workaround, well, works :) Probably worth addressing this somehow better and reopening the issue.
