### ISSUE TITLE
How to override model creation form?

### ISSUE THREAD

**Issue by c-bata** [flask-admin/flask-admin#1244]
Hi, I'd like to override flask-admin's model creation form.
So I override form object like below.

```
from wtforms import PasswordField, StringField, form, Form
from wtforms.validators import DataRequired, Length, EqualTo
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask.ext.admin.contrib.sqla import ModelView

class ShopOwnerForm(form.Form):
    name = StringField(
        'Username',
        validators=[
            DataRequired(),
            Length(max=128),
        ],
    )
    shop = QuerySelectField(
        'Shop Name',
        query_factory=Shop.query.all,
        get_pk=attrgetter('id'),
        get_label=attrgetter('name'),
    )

class ShopOwnerAdmin(ModelView):
    form = ShopOwnerForm
```

But, `sqlalchemy.exc.InvalidRequestError` has occured at following point.

https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L1014

This is the error message .

```
Traceback (most recent call last):
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask_admin/model/base.py", line 1834, in create_view
    model = self.create_model(form)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask_admin/contrib/sqla/view.py", line 1031, in create_model
    if not self.handle_view_exception(ex):
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask_admin/contrib/sqla/view.py", line 1014, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/flask_admin/contrib/sqla/view.py", line 1027, in create_model
    self.session.add(model)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1600, in add
    self._save_or_update_state(state)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1612, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1867, in _save_or_update_impl
    self._save_impl(state)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1835, in _save_impl
    self._before_attach(state)
  File "/Users/zakuro/src/gitlab.com/akashipy/guji_delivery/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1956, in _before_attach
    state.session_id, self.hash_key))
sqlalchemy.exc.InvalidRequestError: Object '<ShopOwner at 0x110d3af98>' is already attached to session '1' (this is '7')
```

**Comment by paggel** [comment]
Try the following example and keep us update if it works. If everything works fine then try to add validators and QuerySelectField.

```
from flask_admin.contrib.sqla import ModelView

class ShopOwnerForm(Form):
    name = StringField('Username')

class ShopOwnerAdmin(ModelView):
    form = ShopOwnerForm
```

**Comment by xqliu** [comment]
I think you can just try to override the create_form or edit_form method from ModelView as below:

```
    def create_form(self, obj=None):
        form = super(ModelView, self).create_form(obj)
        # Do what you would like to do
        form.code.data = Product.get_next_code() #Set up value of a field
        form_util.filter_by_organization(form.category, ProductCategory) #Apply filter
        if not is_super_admin(): # Delete a field from UI.
            delattr(form, "organization")
        return form
```

You may also override scaffold_form method as below:

```
    def scaffold_form(self):
        # Start with the standard form as provided by Flask-Admin. We've already told Flask-Admin to exclude the
        # password field from this form.
        form = super(UserAdmin, self).scaffold_form()

        # Add a password field, naming it "password2" and labeling it "New Password".
        form.password2 = PasswordField(label=lazy_gettext('New Password'),
                                             description=lazy_gettext('Left blank if you don\'t want to change it, '
                                                                      'input the new password to change it'))
        return form
```

Hope the above information helps you.

**Comment by c-bata** [comment]
@paggel Thank you for your comment. As you mentioned, If I replace QuerySelectField into IntegerField, this form is properly working. The cause of this error is QuerySelectField.

@xqliu Thank you very much for your help! When I try to generate a password_confirmation field dynamically in scaffold_form method, I can create a user.

This issue was resolved. Thanks!

**Comment by forlAIght** [comment]
@c-bata  I want to know: (In the @xqliu code:)    
```
        def create_form(self, obj=None):
        form = super(ModelView, self).create_form(obj)
        # Do what you would like to do
        form.code.data = Product.get_next_code() #Set up value of a field
        form_util.filter_by_organization(form.category, ProductCategory) #Apply filter
        if not is_super_admin(): # Delete a field from UI.
            delattr(form, "organization")
        return form
```
      which oject the attribute "is_super_admin"  belong .
     I didn't find it in form, ModelView, and Admin.

**Comment by c-bata** [comment]
Sorry, I don't use flask-admin for a long time.

**Comment by forlAIght** [comment]
> Sorry, I don't use flask-admin for a long time.
anyway, your comment helped me .

**Comment by xqliu** [comment]
> @c-bata I want to know: (In the @xqliu code:)
> 
> ```
>         def create_form(self, obj=None):
>         form = super(ModelView, self).create_form(obj)
>         # Do what you would like to do
>         form.code.data = Product.get_next_code() #Set up value of a field
>         form_util.filter_by_organization(form.category, ProductCategory) #Apply filter
>         if not is_super_admin(): # Delete a field from UI.
>             delattr(form, "organization")
>         return form
> ```
> 
> ```
>   which oject the attribute "is_super_admin"  belong .
>  I didn't find it in form, ModelView, and Admin.
> ```

Hi, in my code is_super_admin() is just a method to decide whether current user is a super admin. it can be any boolean variable or field here.

**Comment by forlAIght** [comment]
@xqliu   the same with my assumptions😀
