### ISSUE TITLE
Better Error Message for Conflicts in ModelView Configuration Attributes

### ISSUE THREAD

**Issue by ye** [flask-admin/flask-admin#1247]
I've spent quite some time to realized a simple mistake made in the ModelView Configuration Attributes: `form_excluded_columns` vs. `form_rules`. As it turned out, the fields should be mutually exclusive between those two buckets. If you put the same field into both buckets, it's gonna give this error:

``` bash
admin_1 | 127.0.0.1 - - [01/Apr/2016 18:25:45] "GET /admin/user/edit/?id=1 HTTP/1.1" 500 -
admin_1 | Traceback (most recent call last):
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
admin_1 |     return self.wsgi_app(environ, start_response)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
admin_1 |     response = self.make_response(self.handle_exception(e))
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
admin_1 |     reraise(exc_type, exc_value, tb)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
admin_1 |     raise value
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
admin_1 |     response = self.full_dispatch_request()
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
admin_1 |     rv = self.handle_user_exception(e)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
admin_1 |     reraise(exc_type, exc_value, tb)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
admin_1 |     raise value
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
admin_1 |     rv = self.dispatch_request()
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
admin_1 |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/base.py", line 68, in inner
admin_1 |     return self._run_view(f, *args, **kwargs)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/base.py", line 367, in _run_view
admin_1 |     return fn(self, *args, **kwargs)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/model/base.py", line 1913, in edit_view
admin_1 |     return_url=return_url)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/base.py", line 307, in render
admin_1 |     return render_template(template, **kwargs)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template
admin_1 |     context, ctx.app)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask/templating.py", line 110, in _render
admin_1 |     rv = template.render(context)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
admin_1 |     return self.environment.handle_exception(exc_info, True)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
admin_1 |     reraise(exc_type, exc_value, tb)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
admin_1 |     raise value.with_traceback(tb)
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/model/edit.html", line 6, in <module>
admin_1 |     <input name="_continue_editing" type="submit" class="btn" value="{{ _gettext('Save and Continue Editing') }}" />
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/master.html", line 1, in <module>
admin_1 |     {% extends admin_base_template %}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 30, in <module>
admin_1 |     {% block page_body %}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 59, in <module>
admin_1 |     {% block body %}{% endblock %}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/model/edit.html", line 36, in <module>
admin_1 |     {% block edit_form %}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/model/edit.html", line 37, in <module>
admin_1 |     {{ lib.render_form(form, return_url, extra(), form_opts) }}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 212, in <module>
admin_1 |     {% call form_tag(action=action) %}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 191, in <module>
admin_1 |     {{ caller() }}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 213, in <module>
admin_1 |     {{ render_form_fields(form, form_opts=form_opts) }}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 174, in <module>
admin_1 |     {{ r(form, form_opts=form_opts) }}
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/form/rules.py", line 109, in __call__
admin_1 |     result.append(r(form, form_opts, field_args))
admin_1 |   File "/usr/local/lib/python3.4/site-packages/flask_admin/form/rules.py", line 305, in __call__
admin_1 |     raise ValueError('Form %s does not have field %s' % (form, self.field_name))
admin_1 | ValueError: Form <flask_admin.contrib.sqla.form.UserForm object at 0x7f8c63cba6a0> does not have field modified_at
```

The offending code is as below:

``` python
from flask.ext.admin.contrib.sqla import ModelView
from flask_admin.form import rules

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    created_at = db.Column(db.DateTime)
    modified_at = db.Column(db.DateTime)


class User(ModelView)
    form_excluded_columns = ['modified_at']

    form_rules = [
        rules.FieldSet(('id', 'username'),
                       'email'),
        rules.FieldSet(('created_at', 'modified_at'),
                       'Meta'),
    ]
```

I am running `Flask-Admin==1.4.0`.  The error was very confusing at first. Perhaps to give a better error message, we should have check the opposing config first before [we raise a ValueError](../blob/v1.4.0/flask_admin/form/rules.py#L305)?

**Comment by petrus-jvrensburg** [comment]
Closing this now. But I agree that it's confusing. A PR to fix this would be welcome.
