### ISSUE TITLE
peewee.ProgrammingError in `in list`/'not in list' filters with empty values using postgres

### ISSUE THREAD

**Issue by discort** [flask-admin/flask-admin#1291]
> Traceback (most recent call last):
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/discort/python/fun/flask-admin/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/discort/python/fun/flask-admin/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/discort/python/fun/flask-admin/flask_admin/model/base.py", line 1815, in index_view
    view_args.search, view_args.filters)
  File "/home/discort/python/fun/flask-admin/flask_admin/contrib/peewee/view.py", line 388, in get_list
    count = query.count() if not self.simple_list_pager else None
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 2893, in count
    return self.aggregate(convert=False) or 0
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 2886, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 2665, in scalar
    row = self._execute().fetchone()
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/discort/python/fun/flask-admin/venv/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
ProgrammingError: syntax error at or near ")"
LINE 1: ...N ("t1"."user_id" = "t2"."id") WHERE ("t2"."username" IN ())

**Comment by discort** [comment]
https://github.com/flask-admin/flask-admin/pull/1292/commits/19fb86f33b544db1dc9e6fc9baffcf1d097db6c7
