### ISSUE TITLE
Error when editing ndb.KeyProperty fields

### ISSUE THREAD

**Issue by kubilus1** [flask-admin/flask-admin#1304]
When a form is using ndb.KeyProperty and you attempt to create a new item or edit an existing item you get the following error:

Traceback (most recent call last):
  File "/home/mkubilus/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mkubilus/Software/afakestore/lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mkubilus/Software/afakestore/lib/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/mkubilus/Software/afakestore/lib/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/mkubilus/Software/afakestore/lib/flask_admin/model/base.py", line 1999, in edit_view
    return_url=return_url)
  File "/home/mkubilus/Software/afakestore/lib/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/home/mkubilus/Software/afakestore/lib/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/mkubilus/Software/afakestore/lib/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/mkubilus/Software/afakestore/lib/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mkubilus/Software/afakestore/lib/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mkubilus/Software/afakestore/lib/flask_admin/templates/bootstrap2/admin/model/edit.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
AttributeError: 'Key' object has no attribute 'key'

This would *appear* to be a templating issue that I've chased to the 'render_field' macro in bootstrap2/admin/lib.html line 137

**Comment by kubilus1** [comment]
This is caused by an old version of wtforms_appengine.  Do not follow the instructions on wtforms_appengine since 'pip install wtforms-appengine' will install a 2 year old version.

Instead:  pip install git+http://www.github.com/wtforms/wtforms-appengine
