### ISSUE TITLE
flask-admin & flask-security, how to use encrypt_password on separate models.py file

### ISSUE THREAD

**Issue by QMickael** [flask-admin/flask-admin#1305]
Hi, 
I try to use flask-admin with flask-security but I meet problem to work with encrypt_password in my models.py. In flask-admin-auth example the model is in app.py but I want separate them.

`models.py`
```python
import datetime
from app import db
from flask_security import UserMixin, RoleMixin
from flask_security.utils import encrypt_password

# Define models
roles_users = db.Table(
    'roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('roles.id'))
)


class User(db.Model, UserMixin):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    is_staff = db.Column(db.Boolean)
    is_moderator = db.Column(db.Boolean)
    active = db.Column(db.Boolean)
    role = db.relationship('Role', secondary=roles_users, backref='users', lazy='dynamic')
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    comments = db.relationship('Comment', backref='author', lazy='dynamic')

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.set_password(password)

    def set_password(self, password_hash):
        self.password = encrypt_password(password_hash)


class Role(db.Model, RoleMixin):
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(40), unique=True)
    description = db.Column(db.String(255))

    def __init__(self, name, description):
        self.name = name
        self.description = description
```

and when I create a new user with command line this error log happen:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 184, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/mickael/Bureau/Projets/flaskBlog/app/models.py", line 32, in __init__
    self.set_password(password)
  File "/home/mickael/Bureau/Projets/flaskBlog/app/models.py", line 35, in set_password
    self.password = encrypt_password(password_hash)
  File "/usr/local/lib/python3.4/dist-packages/flask_security/utils.py", line 148, in encrypt_password
    if _security.password_hash == 'plaintext':
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.4/dist-packages/flask_security/utils.py", line 35, in <lambda>
    _security = LocalProxy(lambda: current_app.extensions['security'])
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.4/dist-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```

Do you have a solution for this problem

**Comment by rochacbruno** [comment]
You have to use app context.

```python
with app.app_context():
    User.create(....)

```

**Comment by mixmastamyk** [comment]
Why is a Flask app context needed to encrypt a password?   Should be unrelated, no?
