### ISSUE TITLE
InlineFormAdmin not displaying primary forms / throws exception in create_model()

### ISSUE THREAD

**Issue by jon-walton** [flask-admin/flask-admin#1372]
Hi,

We're using:
- Flask-Admin 1.4.2
- wtforms 2.1
- sqlalchemy 1.1.1

2 issues are thrown up with the same example code

1) When setting `form_columns` on the `InlineFormAdmin` class, primary keys are not shown on the form

2) If my models have composite primary keys, an exception is thrown when creating a model using `InlineFormAdmin`. This does not happen if using the `ModelView`

trace and example code:

``` text
Traceback (most recent call last):
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\model\base.py", line 1920, in create_view
    model = self.create_model(form)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1028, in create_model
    if not self.handle_view_exception(ex):
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1011, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1023, in create_model
    form.populate_obj(model)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\wtforms\form.py", line 96, in populate_obj
    field.populate_obj(obj, name)
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\contrib\sqla\fields.py", line 280, in populate_obj
    field_id = field.get_pk()
  File "C:\Users\jonwa\Documents\example\.venv\lib\site-packages\flask_admin\model\fields.py", line 121, in get_pk
    return getattr(self.form, self._pk).data
TypeError: getattr(): attribute name must be string
```

``` python
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_admin.model.form import InlineFormAdmin
from flask_sqlalchemy import SQLAlchemy

from sqlalchemy import Column, String, ForeignKey, Enum
from sqlalchemy.orm import relationship
from sqlalchemy_utils import UUIDType

from uuid import uuid4
import enum

class PartnerType(enum.Enum):
    partner1 = 1
    partner2 = 2
    partner3 = 3

class Config(object):
    SECRET_KEY = 'thisisabigsecret'
    SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://devuser:abigsecret@localhost:5432/rewards'

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)

class User(db.Model):
    __tablename__ = 'users'
    id = Column(UUIDType, primary_key=True, default=uuid4)
    email_address = Column(String, unique=True)

    partners = relationship('Partner', back_populates='user')

    def __str__(self):
        return self.email_address


class Partner(db.Model):
    __tablename__ = 'partners'
    user_id = Column(UUIDType, ForeignKey('users.id'))
    partner_user_id = Column(String, primary_key=True)
    partner = Column(Enum(PartnerType, native_enum=True), primary_key=True)
    other_data = Column(String, nullable=True)

    user = relationship('User', back_populates='partners')

    def __str__(self):
        return '{name} - {uid}'.format(name=self.partner.name, uid=self.partner_user_id)


class PartnerInline(InlineFormAdmin):
    column_display_pk = True
    form_columns = ['partner_user_id', 'partner', 'other_data']

class PartnerAdmin(ModelView):
    column_display_pk = True
    form_columns = ['user_id', 'partner_user_id', 'partner', 'other_data']

class UserAdminInline(ModelView):
    column_display_pk = True
    inline_models = (PartnerInline(Partner),)

class UserAdmin(ModelView):
    column_display_pk = True


if __name__ == '__main__':
    db.create_all()

    admin = Admin(template_mode='bootstrap3')
    admin.init_app(app)
    admin.add_view(UserAdmin(User, db.session, name='User Admin', endpoint='useradmin'))
    admin.add_view(UserAdminInline(User, db.session, name='User Inline', endpoint='userinline'))
    admin.add_view(PartnerAdmin(Partner, db.session, name='Partner Admin', endpoint='partneradmin'))

    app.run(port=5000, debug=True)
```

**Comment by dev-zero** [comment]
the second part of this issue is already reported in #672 and has a PR #673

**Comment by petrus-jvrensburg** [comment]
For the first part of the issue:
The primary key fields are not showing up because they are special sqlalchemy_utils UUIDType fields. Related to #1134 and #1465
