### ISSUE TITLE
Search doesn't work on one-to-many relations.

### ISSUE THREAD

**Issue by antoine-lizee** [flask-admin/flask-admin#1398]
`column_display_all_relations = True` successfully displays the one-to-many relations in the list view, but adding one of those in the `column_searchable_list` doesn't work. I bet it's a matter of order at loading?

```
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from app import app
  File "/Volumes/FD/ALAN/alan-backend/app/__init__.py", line 32, in <module>
    from app.admin import admin
  File "/Volumes/FD/ALAN/alan-backend/app/admin.py", line 108, in <module>
    admin.add_view(AdminModelView(model, db.session))
  File "/Volumes/FD/ALAN/alan-backend/app/admin.py", line 93, in __init__
    super().__init__(*args, **kwargs)
  File "/Volumes/FD/ALAN/alan-backend/env/lib/python3.5/site-packages/flask_admin/contrib/sqla/view.py", line 318, in __init__
    menu_icon_value=menu_icon_value)
  File "/Volumes/FD/ALAN/alan-backend/env/lib/python3.5/site-packages/flask_admin/model/base.py", line 771, in __init__
    self._refresh_cache()
  File "/Volumes/FD/ALAN/alan-backend/env/lib/python3.5/site-packages/flask_admin/model/base.py", line 864, in _refresh_cache
    self._search_supported = self.init_search()
  File "/Volumes/FD/ALAN/alan-backend/env/lib/python3.5/site-packages/flask_admin/contrib/sqla/view.py", line 559, in init_search
    for column in tools.get_columns_for_field(attr):
  File "/Volumes/FD/ALAN/alan-backend/env/lib/python3.5/site-packages/flask_admin/contrib/sqla/tools.py", line 118, in get_columns_for_field
    raise Exception('Invalid field %s: does not contains any columns.' % field)
Exception: Invalid field Policy.insurance_profiles: does not contains any columns.
```

**Comment by antoine-lizee** [comment]
FYI, `Policy,insurance_profiles` exists as a relation: 
```
In [3]: Policy.insurance_profiles.__dict__
Out[3]: 
{'__doc__': None,
 '_of_type': None,
 'class_': app.models.policy.Policy,
 'comparator': <sqlalchemy.orm.relationships.RelationshipProperty.Comparator at 0x10c69b7d8>,
 'dispatch': <sqlalchemy.event.base.AttributeEventsDispatch at 0x10d81c228>,
 'impl': <sqlalchemy.orm.attributes.CollectionAttributeImpl at 0x10d750cc0>,
 'key': 'insurance_profiles',
 'property': <RelationshipProperty at 0x10c669d68; insurance_profiles>}
```

**Comment by antoine-lizee** [comment]
No love for long, closing this.
