### ISSUE TITLE
flask-admin/examples/auth broken

### ISSUE THREAD

**Issue by Loknar** [flask-admin/flask-admin#1464]
The `flask-admin/examples/auth` example seems severely outdated, and is also broken as no specific versions were declared in its requirements.txt file, couple of deprecated warnings, and lots of calls to `login.current_user.is_authenticated()` which seems to be not a function but a boolean ..

In its current state, this example isn't helping anyone.

```
(env) loknar@talos:~/Desktop/flask-admin (master)$ python examples/auth/app.py
examples/auth/app.py:3: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy import SQLAlchemy
examples/auth/app.py:5: ExtDeprecationWarning: Importing flask.ext.admin is deprecated, use flask_admin instead.
  from flask.ext import admin, login
examples/auth/app.py:5: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  from flask.ext import admin, login
examples/auth/app.py:6: ExtDeprecationWarning: Importing flask.ext.admin.contrib is deprecated, use flask_admin.contrib instead.
  from flask.ext.admin.contrib import sqla
examples/auth/app.py:6: ExtDeprecationWarning: Importing flask.ext.admin.contrib.sqla is deprecated, use flask_admin.contrib.sqla instead.
  from flask.ext.admin.contrib import sqla
/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
examples/auth/app.py:3: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy import SQLAlchemy
examples/auth/app.py:5: ExtDeprecationWarning: Importing flask.ext.admin is deprecated, use flask_admin instead.
  from flask.ext import admin, login
examples/auth/app.py:5: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  from flask.ext import admin, login
examples/auth/app.py:6: ExtDeprecationWarning: Importing flask.ext.admin.contrib is deprecated, use flask_admin.contrib instead.
  from flask.ext.admin.contrib import sqla
examples/auth/app.py:6: ExtDeprecationWarning: Importing flask.ext.admin.contrib.sqla is deprecated, use flask_admin.contrib.sqla instead.
  from flask.ext.admin.contrib import sqla
/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
* Debugger is active!
 * Debugger PIN: 337-360-916
127.0.0.1 - - [06/Apr/2017 12:17:30] "GET /admin/login/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/loknar/Desktop/flask-admin/env/lib/python2.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/loknar/Desktop/flask-admin/examples/auth/app.py", line 123, in login_view
    if login.current_user.is_authenticated():
TypeError: 'bool' object is not callable
```

**Comment by Speedy1991** [comment]
Is_authenticated

It switched to a property (long time ago...)

**Comment by mrjoes** [comment]
I don't know which version you're testing, but `flask.ext.admin` is not imported in that example, method call was converted to a property long time ago, etc.

https://github.com/flask-admin/flask-admin/blob/master/examples/auth/app.py#L72
