### ISSUE TITLE
QuerySelectField with custom base query class

### ISSUE THREAD

**Issue by cacampbell** [flask-admin/flask-admin#1468]
Hi, I am attempting to use [Flask-SQLAlchemy-Cache](https://github.com/iurisilvio/Flask-SQLAlchemy-Cache) with Flask-Admin and have bumped into an Exception during instantiation of QuerySelectFields.

I have a form like this:

```
class PaperSearchForm(FlaskForm):
    return_url = HiddenField()
    title = StringField()
    abstract = StringField()
    start_date = DateTimeField()
    end_date = DateTimeField()
    doi = StringField()
    pubmed_id = StringField()
    link =  StringField()
    journals = QuerySelectMultipleField(
        query_factory=make_query_factory(Journal),
    )
    authors = QuerySelectMultipleField(
        query_factory=make_query_factory(Author),
    )
    keywords = QuerySelectMultipleField(
        query_factory=make_query_factory(Keyword),
    )
    chapters = QuerySelectMultipleField(
        query_factory=make_query_factory(Chapter),
    )
    printed = BooleanField(default=True)
    unprinted = BooleanField(default=True)
    submit = SubmitField('Search')
```

and the query select function looks like this:

```
# 'model' is the actual model object, imported from models.py
def make_query_factory(model):

    def query_factory(model):
        return db.session.query(model).options(FromCache(cache))

    return query_factory(model)
```

The instantiation in \__init__.py

```
from flask_sqlalchemy_cache import CachingQuery
# ...
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
# ...
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention), query_class=CachingQuery)
# ...

def create_app(config):
# ...
    db.init_app(app)
# ...
```

Clicking "Create" or "Edit" for the views that use QuerySelectFields results in the following:

```
127.0.0.1 - - [12/Apr/2017 15:55:43] "GET /_debug_toolbar/static/css/toolbar.css?0.7762397768527367 HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2017 15:55:47] "GET /paper/ HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2017 15:55:47] "GET /_debug_toolbar/static/css/toolbar.css?0.12396121529467385 HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2017 15:55:48] "GET /paper/new/?url=%2Fpaper%2F HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/python3.5/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/cacampbell/PycharmProjects/coniferbook/app/auth/model_views.py", line 927, in create_view
    return_url=return_url)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/cacampbell/PycharmProjects/coniferbook/app/templates/auth/base.html", line 148, in top-level template code
    <img src="{{ url_for('static', filename='images/loading.gif') }}" />
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 37, in top-level template code
    {% block page_body %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 77, in block "page_body"
    {% block body %}{% endblock %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 22, in block "body"
    {% block create_form %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 23, in block "create_form"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 202, in template
    {% call form_tag(action=action) %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 182, in template
    {{ caller() }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 203, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 175, in template
    {{ render_field(form, f, kwargs) }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 130, in template
    {{ field(**kwargs)|safe }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/form/widgets.py", line 28, in __call__
    return super(Select2Widget, self).__call__(field, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/wtforms/widgets/core.py", line 287, in __call__
    for val, label, selected in field.iter_choices():
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/contrib/sqla/fields.py", line 168, in iter_choices
    for pk, obj in self._get_object_list():
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/contrib/sqla/fields.py", line 100, in _get_object_list
    query = self.query or self.query_factory()
TypeError: 'CachingQuery' object is not callable

```

**Comment by cacampbell** [comment]
Sorry... I just made a mistake when integrating Flask-SQLAlchemy-Cache. 

At some point, I must have rewritten the query factory function incorrectly. 

I have since corrected it and it now looks like:

```
def make_query_factory(model):
    return lambda: model.query.all()
```

This is still using the custom query class, and it works as expected.
