### ISSUE TITLE
Unique validator run before MACAddress validator

### ISSUE THREAD

**Issue by julianiewiejska** [flask-admin/flask-admin#1520]
The unique validator causes problems when used with Postgres types such as MACADDR. Select on a table with an invalid MAC Address will cause an error and I see no easy way to force MAC Address validation to run before the unique validator. Is there a way to disable the unique validator? The only workaround I currently see is to avoid using 'unique=True' in the model altogether.

**Comment by beenje** [comment]
I just bumped in the same issue.

My workaround is to monkey patch the Unique validator from flask-admin to disable it:

```
from flask_admin.contrib import sqla

# Monkey patch flask-admin Unique validator to disable it
sqla.form.Unique.__call__ = lambda x, y, z: None
```

**Comment by abathur** [comment]
I bumped into this as well (though with Ltree values instead). 

We ended up making a new field type to convert values between a string type for the form, and the ORM types. I think this is probably the most-idiomatic approach.

In any case, the error messages here are fairly opaque, and at least in our case occurred in a large stack stack trace that was entirely sqla, flask-admin, wtforms, flask, etc. Even if there's no clear fix here, it would be humane to raise a more specific error here--or at least log a warning--so that it's more obvious that this is a user-fixable issue and not just a compatibility issue between modules.

Here's an example stack:

```
Traceback (most recent call last):
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/4snngfi163xc94h2cwmvrwm3hmb7m18l-python3.6-flask-restplus-0.10.1/lib/python3.6/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/nix/store/4snngfi163xc94h2cwmvrwm3hmb7m18l-python3.6-flask-restplus-0.10.1/lib/python3.6/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nix/store/0cpxr6y9wghj4bmvrgdwa6dk30k36h5d-python3.6-Flask-0.12.2/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nix/store/bwqr0injyycddpfwxysi801y995ahn8h-python3.6-Flask-Admin-1.5.5/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/nix/store/bwqr0injyycddpfwxysi801y995ahn8h-python3.6-Flask-Admin-1.5.5/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/nix/store/bwqr0injyycddpfwxysi801y995ahn8h-python3.6-Flask-Admin-1.5.5/lib/python3.6/site-packages/flask_admin/model/base.py", line 2086, in create_view
    if self.validate_form(form):
  File "/nix/store/bwqr0injyycddpfwxysi801y995ahn8h-python3.6-Flask-Admin-1.5.5/lib/python3.6/site-packages/flask_admin/model/base.py", line 1382, in validate_form
    return validate_form_on_submit(form)
  File "/nix/store/bwqr0injyycddpfwxysi801y995ahn8h-python3.6-Flask-Admin-1.5.5/lib/python3.6/site-packages/flask_admin/helpers.py", line 72, in validate_form_on_submit
    return is_form_submitted() and form.validate()
  File "/nix/store/zzsri88dahy8gkhxg6cgync60xc9jv5a-python3.6-WTForms-2.2.1/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/nix/store/zzsri88dahy8gkhxg6cgync60xc9jv5a-python3.6-WTForms-2.2.1/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/nix/store/zzsri88dahy8gkhxg6cgync60xc9jv5a-python3.6-WTForms-2.2.1/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/nix/store/zzsri88dahy8gkhxg6cgync60xc9jv5a-python3.6-WTForms-2.2.1/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/nix/store/bwqr0injyycddpfwxysi801y995ahn8h-python3.6-Flask-Admin-1.5.5/lib/python3.6/site-packages/flask_admin/contrib/sqla/validators.py", line 37, in __call__
    .filter(self.column == field.data)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3358, in one
    ret = self.one_or_none()
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3327, in one_or_none
    ret = list(self)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3403, in __iter__
    return self._execute_and_instances(context)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3428, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1175, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 834, in _init_compiled
    for key in compiled_params
  File "/nix/store/g3xs0m74n3yl755l17cm838zlr5ca7gj-python3.6-SQLAlchemy-1.3.15/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 834, in <genexpr>
    for key in compiled_params
  File "/nix/store/yakl48d7c2869lg8xabmf43s9vvl4yh9-python3.6-SQLAlchemy-Utils-0.33.6/lib/python3.6/site-packages/sqlalchemy_utils/types/ltree.py", line 68, in process
    return value.path
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'str' object has no attribute 'path'
[SQL: SELECT content.id AS content_id, content.path AS content_path, content.parent_id AS content_parent_id, content.number AS content_number, content.show_num AS content_show_num, content.name AS content_name, content.description AS content_description, content.free_content AS content_free_content, content.topic_id AS content_topic_id, content._discriminator AS content__discriminator, content.purchase_url AS content_purchase_url, content.market AS content_market, content.type AS content_type, content.lb_path AS content_lb_path, content._name_template AS content__name_template, content.media_id AS content_media_id 
FROM content 
WHERE content.lb_path = %(lb_path_1)s AND content._discriminator IN (%(discriminator_1)s, %(discriminator_2)s)]
[parameters: [immutabledict({})]]
```
