### ISSUE TITLE
Unable to make columns searchable with peewee

### ISSUE THREAD

**Issue by mssdvd** [flask-admin/flask-admin#1629]
Hello I'm trying to make column searchable but I always get this traceback:
```
Traceback (most recent call last):
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask_admin/model/base.py", line 1882, in index_view
    view_args.search, view_args.filters, page_size=page_size)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask_admin/contrib/peewee/view.py", line 373, in get_list
    query = self._handle_join(query, field, joins)
  File "/home/davide/.local/share/virtualenvs/fleetManagement-MJmDDqk_/lib/python3.6/site-packages/flask_admin/contrib/peewee/view.py", line 310, in _handle_join
    if field.model_class != self.model:
AttributeError: 'CharField' object has no attribute 'model_class'
```
This is the view class:
```python
class FleetManagementView(ModelView):
    can_export = True
    can_view_details = True


class DriversView(FleetManagementView):
    column_searchable_list = ['surname']
    column_editable_list = ['name', 'surname', 'birth']
    column_sortable_list = ['id', 'name', 'surname', 'birth']
```
And this is the model:
```python

class Drivers(BaseModel):
    class Meta:
        table_name = "drivers"

    id = AutoField()
    name = CharField(null=False)
    surname = CharField(null=False)
    birth = DateField()

    def __str__(self):
        return f"{self.name} {self.surname}"
```

**Comment by MaxNoe** [comment]
I get the same error when trying to sort (Clicking on the column name)

**Comment by petrus-jvrensburg** [comment]
This is an issue when running Peewee on Python 3. I opened #1721 for addressing this.
