### ISSUE TITLE
Adding views to an application factory

### ISSUE THREAD

**Issue by mathewtrivett** [flask-admin/flask-admin#1799]
```
Flask-SQLAlchemy==2.3.2
Flask-Admin==1.5.3
Flask==1.0.2
```
I'm trying to register views on an Flask Admin object using the application factory pattern. I think there have been a few issues raised with application factories. I couldn't seem to figure out a solution so I thought I'd post here.

I have a `create_app` function in a module called `factory.py` that looks like this.

```
from .api.v1.admin import views as admin_views
from .core import db

def create_app(config = None, env = None):
    app = Flask(__name__)

    if env is None:
        app.env = os.environ.get('SERVER_ENV')
    else:
        app.env = env

    load_settings(app)
    db.init_app(app)
    migrate.init_app(app, db)
    security.init_app(app, user_datastore)

    #mail.init_app(app)
    register_blueprints(app)
    admin = Admin(app, name='App name', template_mode='bootstrap3')
    admin.add_views(*admin_views)
    return app
```

In `api.v1.admin` there is a list of views passed to admin's add_views method:
```
from flask_admin.contrib.sqla import ModelView
from ...models.users import User, Role
from ...core import db

views = [
    ModelView(User, db.session, category="Users"),
    ModelView(Role, db.session, category="Users"),
   ...
]
```
It appears to register the models:
![screen shot 2019-01-24 at 20 11 26](https://user-images.githubusercontent.com/1696963/51705728-47f23080-2014-11e9-8a4b-d20c3e0ed43b.png)

But when I go to edit either the User or Role model in the browser I get an Internal Server Error and the below Stacktrace. I'm trying to figure out whether this is an issue with the way I'm initialising flask admin or an issue with SQL Alchemy. The database exists and is set and loaded through an environment variable.

Any help or advice greatly appreciated.

```
Traceback (most recent call last):
  File "/vagrant/venv3/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/vagrant/venv3/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/vagrant/venv3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_admin/model/base.py", line 1960, in index_view
    view_args.search, view_args.filters, page_size=page_size)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_admin/contrib/sqla/view.py", line 1029, in get_list
    query = self.get_query()
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_admin/contrib/sqla/view.py", line 839, in get_query
    return self.session.query(self.model)
  File "/vagrant/venv3/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/vagrant/venv3/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/vagrant/venv3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3010, in __call__
    return self.class_(**local_kw)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 143, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 877, in engine
    return self.get_engine()
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 556, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "/vagrant/venv3/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 830, in apply_driver_hacks
    if info.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
```

**Comment by mathewtrivett** [comment]
I figured it out, this configuration is actually right and fine. But thought I’d share this in case people encounter similar issues.

Flask wasn’t loading environment variables possibly because Supervisor sets up its own environment?

Anyway I used python-dotenv and an .env role to set env vars and now it works like a dream. Closing this issue
