### ISSUE TITLE
New theme - bootstrap 4

### ISSUE THREAD

**Issue by Fomys** [flask-admin/flask-admin#1845]
Hello,
I am currently writing a new theme for flask-admin, but after some modifications (I can't find which ones, I keep looking), the rendering of inline forms is a problem: `AttributeError:'str' object has no attribute' get_pk'`

You can check source code here: [LBI_PiPy](https://github.com/Fomys/LBI_PiPy)

I only override templates in templates/admin, replace most of vendor script by bs4 compatible ones (in static/external), add simple css in static/admin/css.

When I'm done I could make a pull request if anyone is interested (I see that #1486 is inactive).

Full error here:
```Traceback (most recent call last):
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\model\base.py", line 2155, in edit_view
    return_url=return_url)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\base.py", line 308, in render
    return render_template(template, **kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\model\edit.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\templates\bootstrap3\admin\master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\base.html", line 40, in top-level template code
    {% block page_body %}
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\base.html", line 82, in block "page_body"
    {% block body %}{% endblock %}
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\model\edit.html", line 32, in block "body"
    {% block edit_form %}
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\model\edit.html", line 33, in block "edit_form"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\lib.html", line 206, in template
    {% call form_tag(action=action) %}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\lib.html", line 185, in template
    {{ caller() }}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\lib.html", line 207, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\lib.html", line 177, in template
    {{ render_field(form, f, kwargs) }}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\lib.html", line 132, in template
    {{ field(**kwargs)|safe }}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\model\fields.py", line 38, in __call__
    **kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\form\widgets.py", line 103, in __call__
    return template.render(kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\templates\bootstrap3\admin\model\inline_field_list.html", line 15, in top-level template code
    {{ base.render_inline_fields(field, template, render_field, check) }}
  File "D:\Users\fomys\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Users\fomys\Github\LBI_PiPy\LBI_PiPy\templates\admin\model\inline_list_base.html", line 9, in template
    {%- if not check or check(subfield) %}
  File "D:\Users\me}\.virtualenvs\LBI_PiPy-iofJb-eu\lib\site-packages\flask_admin\contrib\sqla\fields.py", line 291, in display_row_controls
    return field.get_pk() is not None
AttributeError: 'str' object has no attribute 'get_pk'
```

With a print I can see that field string is:
```<div class="inline-form-field">
<input id="versions-0-id" name="versions-0-id" type="hidden" value="1">
    <div class="form-group">
        <label for="versions-0-version" class="col-md-3 control-label">Version
            &nbsp;
        </label>
        <div class="col-md-10">
            <input class="form-control" id="versions-0-version" name="versions-0-version" type="text" value="0.0.1">
        </div>
    </div>
</div>
&nbsp;
```

Can someone tell me where is my error, or at least one track to solve my problem?
Thanks by advance,
Fomys

**Comment by ufo911** [comment]
There is a pull request for BS 4 https://github.com/flask-admin/flask-admin/pull/1674

**Comment by Fomys** [comment]
Great, I didn't see it.
So I will use this version to make a theme with a menu bar on the left.
Thank you very much.
