### ISSUE TITLE
Error running sqla app.py/run_server.py 

### ISSUE THREAD

**Issue by timhughes** [flask-admin/flask-admin#1881]
Using the instructions in the README.rst the example app at `python examples/sqla/app.py` is broken after. 
```
857d9f5f Merge pull request #1728 from flask-admin/fix-search-placeholder
```

At f6198b45 I get the following error 

```
hughest@argon [0] $ python examples/sqla/app.py 
/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "examples/sqla/app.py", line 327, in <module>
    admin.add_view(UserAdmin(User, db.session))
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 329, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/model/base.py", line 945, in _refresh_cache
    self._refresh_filters_cache()
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/model/base.py", line 847, in _refresh_filters_cache
    self._filters = self.get_filters()
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/model/base.py", line 1165, in get_filters
    raise Exception('Unsupported filter type %s' % n)
Exception: Unsupported filter type email
```

At the current master 2d43a263 I get the following error.

```
hughest@argon [0] $ python examples/sqla/run_server.py 
Traceback (most recent call last):
  File "examples/sqla/run_server.py", line 1, in <module>
    from admin import app
  File "/home/hughest/tmp/flask-admin/examples/sqla/admin/__init__.py", line 24, in <module>
    import admin.main
  File "/home/hughest/tmp/flask-admin/examples/sqla/admin/main.py", line 248, in <module>
    admin.add_view(UserAdmin(User, db.session))
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 329, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/model/base.py", line 913, in _refresh_cache
    self._search_supported = self.init_search()
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 578, in init_search
    for column in tools.get_columns_for_field(attr):
  File "/home/hughest/tmp/flask-admin/env/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 123, in get_columns_for_field
    raise Exception('Invalid field %s: does not contains any columns.' % field)
Exception: Invalid field User.phone_number: does not contains any columns.
```

**Comment by petrus-jvrensburg** [comment]
The example has been updated to reflect the latest changes on 'master', so the version of Flask-Admin that you have installed can't handle those yet. 

You can either try an older version of the example, or you can install the latest master and run it agains that. To install the package version that you've got checked-out locally, you can 

```
pip uninstall flask-admin
pip install -e .
```
where `.` is the path to the root of the repo, where `setup.py` is located.

**Comment by MarcanX** [comment]
Even with the latest version of master, the example doesn't work, any more ideas please?

**Comment by yeongseon** [comment]
Looks like this example is now working. :(
