### ISSUE TITLE
Flask Admin is broken by Werkzeug 1.0.0

### ISSUE THREAD

**Issue by satshabad-cr** [flask-admin/flask-admin#1951]
Apologizes if this is wrong place to post this, but using pipenv and depending on the latest version of flask-admin, we get this.

```
Traceback (most recent call last):
  File "run_www.py", line 4, in <module>
    from www.entry import app
  File "/app/www/entry.py", line 110, in <module>
    import www.views.admin  # noqa
  File "/app/www/views/admin.py", line 5, in <module>
    from flask_admin.contrib.sqla import ModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/view.py", line 19, in <module>
    from flask_admin.model import BaseModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/model/__init__.py", line 2, in <module>
    from .base import BaseModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/usr/local/lib/python3.8/site-packages/werkzeug/__init__.py)
```

**Comment by davidism** [comment]
Looks like this was fixed by #1922 but may not have been released yet.

**Comment by laundry-96** [comment]
Is there a workaround until this is released, or will this be released soon? Could I possibly force the installation of werkzeug 0.16.1 from flask-admin?

**Comment by rrcc0044** [comment]
I tried downgrading werkzeug==0.16.1 and it worked

**Comment by levsa** [comment]
> Is there a workaround until this is released, or will this be released soon? Could I possibly force the installation of werkzeug 0.16.1 from flask-admin?

If you add `werkzeug==0.16.1` to your requirements file, flask-admin will use that, since it only requires `werkzeug>=0.7`

**Comment by ddelange** [comment]
ref https://github.com/pallets/flask/pull/3489

**Comment by mrjoes** [comment]
I'm doing a release today.

**Comment by mrjoes** [comment]
We're back in action.

**Comment by rrcc0044** [comment]
Thank you for your work!

**Comment by ashb** [comment]
:heart: Thanks @mrjoes
