### ISSUE TITLE
sqlalchemy.exc.NoInspectionAvailable using SQLAlchemy 1.4

### ISSUE THREAD

**Issue by leducvin** [flask-admin/flask-admin#2101]
Very similar to #1976, but with slightly different error message.
Same minimal working example as https://github.com/flask-admin/flask-admin/issues/1976#issue-596644327.

SQLAlchemy 1.4.5
flask 1.1.2
flask-admin 1.5.7
python 3.8

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    admin.add_view(ChildView(Child, Session))
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/contrib/sqla/view.py", line 327, in __init__
    super(ModelView, self).__init__(model, name, category, endpoint, url, static_folder,
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/model/base.py", line 945, in _refresh_cache
    self._refresh_filters_cache()
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/model/base.py", line 847, in _refresh_filters_cache
    self._filters = self.get_filters()
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/model/base.py", line 1161, in get_filters
    flt = self.scaffold_filters(n)
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/contrib/sqla/view.py", line 661, in scaffold_filters
    is_hybrid_property = tools.is_hybrid_property(self.model, name)
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/contrib/sqla/tools.py", line 214, in is_hybrid_property
    return last_name in get_hybrid_properties(last_model)
  File "/tmp/venv/lib/python3.8/site-packages/flask_admin/contrib/sqla/tools.py", line 195, in get_hybrid_properties
    for key, prop in inspect(model).all_orm_descriptors.items()
  File "/tmp/venv/lib/python3.8/site-packages/sqlalchemy/inspection.py", line 71, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'str'>
```

**Comment by mrjoes** [comment]
This is fixed in a master branch, but we're blocked by sqlalchemy-utils dependency to make a new release: https://github.com/kvesteri/sqlalchemy-utils/issues/505

**Comment by leducvin** [comment]
OK, thanks. Looking forward to an upcoming new release.

**Comment by HusseinKabbout** [comment]
`sqlalchemy-utils` made a new release two days ago. (https://github.com/kvesteri/sqlalchemy-utils/releases/tag/0.37.0)

@mrjoes When do you think the new release will take place for `flask-admin`?

**Comment by mrjoes** [comment]
New build is out.
