### ISSUE TITLE
importing ModelView is giving me an error.

### ISSUE THREAD

**Issue by AlexFrazer** [flask-admin/flask-admin#587]
whenever I try `from flask.ext.admin.contrib.sqla import ModelView`, I get the following traceback. I am using python 3.4

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from innovation_center.app import create_app
  File "/home/crow/code/innovation_center/innovation_center/app/__init__.py", line 6, in <module>
    from flask.ext.admin.contrib.sqla import ModelView
  File "/home/crow/code/flask/lib/python3.4/site-packages/flask_admin/contrib/sqla/__init__.py", line 1, in <module>
    from .view import ModelView
  File "/home/crow/code/flask/lib/python3.4/site-packages/flask_admin/contrib/sqla/view.py", line 16, in <module>
    from flask.ext.admin.contrib.sqla import form, filters, tools
  File "/home/crow/code/flask/lib/python3.4/site-packages/flask_admin/contrib/sqla/form.py", line 20, in <module>
    from wtforms.ext.dateutil.fields import DateTimeField
  File "/home/crow/code/flask/lib/python3.4/site-packages/wtforms/ext/dateutil/fields.py", line 6, in <module>
    from dateutil import parser
  File "/home/crow/code/flask/lib/python3.4/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
```

**Comment by RyanPaulMcKenna** [comment]
The documentation says they support python 2.7 and 3.3 or higher.
