### ISSUE TITLE
[Mongoengine] Inner field error for `ListField(EmbeddedDocumentField(Model))`

### ISSUE THREAD

**Issue by bocribbz** [flask-admin/flask-admin#725]
eg. `users = ListField(EmbeddedDocumentField(User))`

Assuming `User` has a required field that is missing or an URL field that is invalid, on form submit it doesnt display field errors, instead raises the following:

```
Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/env/src/flask-admin/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/env/src/flask-admin/flask_admin/base.py", line 344, in _run_view
    return fn(self, *args, **kwargs)
  File "/env/src/flask-admin/flask_admin/model/base.py", line 1365, in edit_view
    if self.update_model(form, model):
  File "/env/src/flask-admin/flask_admin/contrib/mongoengine/view.py", line 538, in update_model
    error=format_error(ex)),
  File "/env/src/flask-admin/flask_admin/contrib/mongoengine/helpers.py", line 35, in format_error
    return '. '.join(itervalues(error.to_dict()))
TypeError: sequence item 0: expected string, dict found
```

Sample value for `error.to_dict()` in this scenario:
` {'users': {0: {'url': u'Invalid URL: 123'}}}`

**Comment by gordol** [comment]
This is still happening for me as well... 

So, let's dig in... :)

In debug mode a ValidaitonError is thrown, ex: 

```
ValidationError: ValidationError (Client:551c938013d5342d2d00f751) (6.report_templates.Field is required and cannot be empty: ['inspection_types'])
```

However, the behavior changes when debug mode is off.

In mongoengine/view.py we have this:
```
            if not self.handle_view_exception(ex):
                flash(gettext('Failed to create record. %(error)s',
                              error=format_error(ex)),
                      'error')
                log.exception('Failed to create record.')
```

From model/base.py:
```python
    # Exception handler
    def handle_view_exception(self, exc):
        if isinstance(exc, ValidationError):
            flash(as_unicode(exc))
            return True

        if self._debug:
            raise

        return False
```

The format_error method looks like this:
```python

def format_error(error):
    if isinstance(error, ValidationError):
        return '. '.join(itervalues(error.to_dict()))

    return as_unicode(error)
```

ValidationError is thrown, in debug mode. 

But when *not* in debug mode, handle_view_exception() must be returning false, because we're calling format_error() in a conditional that says ```if not self.handle_view_exception(ex)```. 

For handle_view_exception() to return false, this must be true: ```isinstance(exc, ValidationError)```. 

So, format_error() checks if the error is a ValidationError too, and if it's not, it should be passing it through as_unicode(), but it's not, it's passing it through ```join(itervalues(error.to_dict()))```.

Thus, the only possibility is that not all ValidationError's are the same.

In models/base.py we have the following:

```python
from wtforms.validators import ValidationError, Required
```

but in mongoengine.helpers.py we have the following:

```python
from mongoengine import ValidationError
```

**Comment by gordol** [comment]
Wheeeee that was a fun little code dive 😆

**Comment by gordol** [comment]
To be clear there are two issues here... Validation failing in wtforms, and validation failing in mongoengine... I was having problems with mongoengine, but you were having problems with wtforms... Both are fixed now, though, it seems.

**Comment by gordol** [comment]
wtforms:
![WTF Validation Field](https://node.zeneval.com/snaps/813d62d91920674938167dd0f290ba60.png)
![WTF Validation Flash](https://node.zeneval.com/snaps/de0346d207c84e176f23fe784949c535.png)

mongoengine:
![Mongoengine Validation Field](https://node.zeneval.com/snaps/869bc350307e212b1c84270eae27847f.png)
![Mongoengine Validation Flash](https://node.zeneval.com/snaps/f3875bb7c4ab4a9571d734051b18c595.png)

**Comment by bocribbz** [comment]
Ops sorry, i forgot this issue open.
Actually the fix for my problem was in #724

**Comment by gordol** [comment]
Hmm, okay so my issue is ever so slightly different then. I'll move the discussion over there then.

**Comment by gordol** [comment]
Actually, I think that #724 is a different issue... Hmm... I'm tired, I'll have to review this again tomorrow...

When a mongo document error is thrown in a list of embedded documents, like you documented, I have the same traceback thrown.


```
Traceback (most recent call last):
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_admin/base.py", line 354, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_admin/model/base.py", line 1519, in edit_view
    if self.update_model(form, model):
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 564, in update_model
    error=format_error(ex)),
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/helpers.py", line 34, in format_error
    return '. '.join(itervalues(error.to_dict()))
TypeError: sequence item 0: expected string, dict found

```

**Comment by gordol** [comment]
Yeah, the issue outlined in our tracebacks is most assuredly not fixed currently. My pull request does fix it, however.

**Comment by gordol** [comment]
FYI, since you closed this I moved this discussion over here: https://github.com/flask-admin/flask-admin/pull/1262
