### ISSUE TITLE
Issues migrating from flask-admin 1.0.7 to 1.2.0

### ISSUE THREAD

**Issue by sbehrens** [flask-admin/flask-admin#967]
I've been working through a number of issues during the migration process but seem to be rather stumped on this issue.  

I have some backrefs and other things that used to work in 1.0.7.  Looking through the documentation I am unsure what changed or why this would stop working.  Any ideas?

```bash
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    from sleepypuppy.admin.admin.models import Administrator
  File "/Users/sbehrens/dev/sleepy-puppy/sleepypuppy/__init__.py", line 126, in <module>
    flask_admin.add_view(PayloadView(db.session))
  File "/Users/sbehrens/dev/sleepy-puppy/sleepypuppy/admin/payload/views.py", line 117, in __init__
    super(PayloadView, self).__init__(Payload, session, **kwargs)
  File "/Users/sbehrens/dev/sleepy-puppy/leepy/lib/python2.7/site-packages/Flask_Admin-1.2.0-py2.7.egg/flask_admin/contrib/sqla/view.py", line 291, in __init__
    menu_icon_value=menu_icon_value)
  File "/Users/sbehrens/dev/sleepy-puppy/leepy/lib/python2.7/site-packages/Flask_Admin-1.2.0-py2.7.egg/flask_admin/model/base.py", line 587, in __init__
    self._refresh_cache()
  File "/Users/sbehrens/dev/sleepy-puppy/leepy/lib/python2.7/site-packages/Flask_Admin-1.2.0-py2.7.egg/flask_admin/model/base.py", line 664, in _refresh_cache
    self._sortable_columns = self.get_sortable_columns()
  File "/Users/sbehrens/dev/sleepy-puppy/leepy/lib/python2.7/site-packages/Flask_Admin-1.2.0-py2.7.egg/flask_admin/contrib/sqla/view.py", line 511, in get_sortable_columns
    column, path = self._get_field_with_path(c)
  File "/Users/sbehrens/dev/sleepy-puppy/leepy/lib/python2.7/site-packages/Flask_Admin-1.2.0-py2.7.egg/flask_admin/contrib/sqla/view.py", line 337, in _get_field_with_path
    value = getattr(model, attribute)
AttributeError: type object 'Payload' has no attribute 'assessments'
```

*Assessment model*
```python
class Assessment(db.Model):
    """
    Assessemt model contains the following parameters:

    name = name of the assessment you are working on.
    payloads = payloads assocaited with the assessment
    """
    __tablename__ = 'assessments'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(500))
    payloads = db.relationship("Payload", secondary=assessment_associations, backref="assessments")

    def as_dict(self):
        """Return Assessment model as JSON object"""
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self):
        return str(self.name)
```

*Payload Model*
```python
class Payload(db.Model):
    """
    Payload model contains the following parameters:

    payload = payload used in injection testing.
    url = url where payload is submitted to
    method = method of request to faciliate xss testing
    paramater = parameter which contains the payload
    notes = notes
    """
    __tablename__ = 'payloads'

    id = db.Column(db.Integer, primary_key=True)
    payload = db.Column(db.String(500))
    url = db.Column(db.String(500))
    method = db.Column(db.String(12))
    parameter = db.Column(db.String(50))
    notes = db.Column(db.String(200))
    assessment = db.Column(db.Integer, db.ForeignKey('assessments.id'))

    # When payloads are deleted, cascade the delete and remove associated captures
    captures = db.relationship("Capture", cascade="all,delete", backref="payloads")
```

**Comment by mrjoes** [comment]
This one is strange. You're referencing `Payload.assessments` from your admin panel, but it is not there. As I can see, it is a `backref` set on a `Assessment` model. 

Can you check in python console if there's a `Payload.assessments` property (module with `Assessment` is getting loaded, etc)?

**Comment by sbehrens** [comment]
resolved.
