### ISSUE TITLE
TypeError using geo_alchemy demo app

### ISSUE THREAD

**Issue by bekerov** [flask-admin/flask-admin#968]
Hello. Help please. 
After send form for create item (line, polygon, etc.) i have this error:
TypeError
TypeError: object of type 'int' has no len()

But after this item in list of polygons. And its creates perfeclty
I cant figure out how i can fix this problem.

**Comment by petrus-jvrensburg** [comment]
I'm not seeing any errors when adding a line at the example app at http://examples.flask-admin.org/geo/admin/linestring/. 

<img width="273" alt="screen shot 2015-08-01 at 8 42 51 am" src="https://cloud.githubusercontent.com/assets/3660183/9020925/82abca3c-3829-11e5-93e1-8b5559225763.png">

Did you follow the steps in the README at https://github.com/flask-admin/flask-admin/tree/master/examples/geo_alchemy?

Can you post a full traceback?

**Comment by bekerov** [comment]
I think postgis installed incorreclty. May be you have full instruction on Ubuntu Server 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

`
Traceback (most recent call last):
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/var/www/app/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/var/www/app/lib/python2.7/site-packages/flask/sessions.py", line 326, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/var/www/app/lib/python2.7/site-packages/itsdangerous.py", line 566, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/var/www/app/lib/python2.7/site-packages/itsdangerous.py", line 412, in sign
    return value + sep + self.get_signature(value)
  File "/var/www/app/lib/python2.7/site-packages/itsdangerous.py", line 347, in get_signature
    key = self.derive_key()
  File "/var/www/app/lib/python2.7/site-packages/itsdangerous.py", line 336, in derive_key
    mac = hmac.new(self.secret_key, digestmod=self.digest_method)
  File "/usr/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 68, in __init__
    if len(key) > blocksize:
TypeError: object of type 'int' has no len()
`

**Comment by petrus-jvrensburg** [comment]
The 'examples' site is currently running on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64). 

I have the following as part of the setup:

    sudo apt-get install build-essential python python-dev libpq-dev
    sudo apt-get install postgresql postgresql-contrib
    sudo apt-get install postgis*

**Comment by bekerov** [comment]
After reinstall packages same error

**Comment by bekerov** [comment]
This error because i set up SECRET_KEY = 12345
Change to SECRET_KEY = "12345" fix my problem
Thanks

**Comment by petrus-jvrensburg** [comment]
Ah, that's great. I'm glad you found the problem!

There is one known bug with the `geo_alchemy` demo to be aware of: if you are planning on using the MULTI-shape geometries, then the Leaflet javascript plugin lets you create them, but it won't let you edit them. See #861.

But you'll see that bug on the 'examples' site too.
