### ISSUE TITLE
Daterangepicker, issues with custom date format

### ISSUE THREAD

**Issue by plaes** [flask-admin/flask-admin#987]
Currently, the daterangepicker widget bundled with flask-admin has issue with custom date formats.
When I change the default date format to ones below and start typing the date, daterangepicker widget tries immediately load the typed date (year as first element) and sadness ensues.

    form_args = {
        'date_column': dict(format='%d.%m.%Y')
    }
    form_widget_args = {
        'date_column': {'data-date-format': 'DD.MM.YYYY'}
    }

This issue seems to be fixed with daterangepicker-2.0.8, but its properties have changed compared to 1.3.xx.

**Comment by pawl** [comment]
I looked into upgrading to 2.0.8 and noticed two complications:
* Date format was configured with ```format: 'YYYY-MM-DD'```, but now it's inside of locale: ```locale: {format: 'YYYY-MM-DD'}```. I think this breaks the ability to set the format with html5 data attributes?
* Dropped support for bootstrap 2.

**Comment by plaes** [comment]
Yeah, forgot to mention that it cannot be easily upgraded to. And it might not support empty input: dangrossman/bootstrap-daterangepicker#771

**Comment by plaes** [comment]
There's another issue I ran into because of the invalid formatting. When user accidentally inputs 10.10.0001, then following happens:

```
Traceback (most recent call last):
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/model/base.py", line 1729, in edit_view
    return_url=return_url)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/base.py", line 299, in render
    return render_template(template, **kwargs)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/plaes/code/topsecretapp/app/templates/_reader_edit.html", line 1, in top-level template code
    {% extends 'admin/model/edit.html' %}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/model/edit.html", line 5, in top-level template code
    <input name="_continue_editing" type="submit" class="btn btn-default" value="{{ _gettext('Save and Continue') }}" />
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/plaes/code/topsecretapp/app/templates/base.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/base.html", line 30, in top-level template code
    {% block page_body %}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/base.html", line 69, in block "page_body"
    {% block body %}{% endblock %}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/model/edit.html", line 30, in block "body"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/lib.html", line 202, in template
    {% call form_tag(action=action) %}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/lib.html", line 182, in template
    {{ caller() }}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/lib.html", line 203, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/lib.html", line 166, in template
    {{ r(form, form_opts=form_opts) }}
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/form/rules.py", line 316, in __call__
    return super(Field, self).__call__(form, form_opts, params)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/form/rules.py", line 208, in __call__
    return macro(**opts)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/templates/bootstrap3/admin/lib.html", line 130, in template
    {{ field(**kwargs)|safe }}
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/wtforms/fields/core.py", line 149, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/wtforms/meta.py", line 53, in render_field
    return field.widget(field, **render_kw)
  File "/home/plaes/.virtualenvs/flask-admin/src/flask-admin-master/flask_admin/form/widgets.py", line 53, in __call__
    return super(DatePickerWidget, self).__call__(field, **kwargs)
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/wtforms/widgets/core.py", line 157, in __call__
    kwargs['value'] = field._value()
  File "/home/plaes/.virtualenvs/flask-admin/lib/python2.7/site-packages/wtforms/fields/core.py", line 727, in _value
    return self.data and self.data.strftime(self.format) or ''
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by plaes** [comment]
Quick hack I came up with, in case anyone else runs into similar issue:
```
    # Please note that date_field is specific to your model
    def validate_form(self, form):
        if super(WorkerBaseView, self).validate_form(form):
            # Check whether date format is actually supported
            d = form.date_field.data
            if d:
                try:
                    form.date_field.data.strftime('%d.%m.%Y')
                except ValueError:
                    form.date_field.errors.append('Year must be >= 1900')
                    return False
            return True
        return False
