### ISSUE TITLE
column_filters is not compatible with babel

### ISSUE THREAD

**Issue by litnimax** [flask-admin/flask-admin#988]
Using current master.
When adding:

```
column_labels = dict(
        created=lazy_gettext('Created'),
        message=lazy_gettext('Message'),
    )
column_filters = ['created', 'message']
```

get the following error:

```
127.0.0.1 - - [13/Aug/2015 19:13:17] "GET /logbook/?sort=1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/model/base.py", line 1636, in index_view
    return_url=self._get_list_url(view_args),
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/base.py", line 299, in render
    return render_template(template, **kwargs)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/list.html", line 5, in top-level template code
    {% import 'admin/actions.html' as actionlib with context %}
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/max/tmp-work/astbarrier/templates/my_master.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 80, in top-level template code
    {% block tail %}
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/list.html", line 207, in block "tail"
    {{ filter_groups|tojson|safe }},
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/json.py", line 243, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/json.py", line 186, in htmlsafe_dumps
    rv = dumps(obj, **kwargs) \
  File "/home/max/tmp-work/astbarrier/env/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 382, in _iterencode_dict
    raise TypeError("key " + repr(key) + " is not a string")
TypeError: key lu'\u0421\u043e\u0437\u0434\u0430\u043d\u043e' is not a string

```

The following can be a fix:

```
class FiltersFixMixin(object):

    def scaffold_filters(self, name):
        filters = super(FiltersFixMixin, self).scaffold_filters(name)

        def fix_filter(filter):
            filter.name = filter.name.encode('utf-8')
            return filter

        return map(fix_filter, filters)
```

But it does not add translation to filters.
Please advise.

**Comment by torotil** [comment]
While fixing the immediate error this workaround undos the translateability of the label. The output of `scaffold_filters` is generated on ModelBaseView initialization and then cached … and it used as label of the filter-groups in the interface.

**Comment by torotil** [comment]
Here is the information from the closed duplicate:

There seems to be a conflict with lazy_gettext translated column_labels. Here is a minimal example to demonstrate the issue:
```python
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_babelex import lazy_gettext
from flask_sqlalchemy import SQLAlchemy

app = Flask('test')
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String())

class UserModelView(ModelView):
    column_labels = {'name': lazy_gettext('User name')}
    column_filters = ('name', )

admin = Admin(app, index_view=UserModelView(User, db.session, url='/'))

if __name__ == '__main__':
    app.run()
```

The app fails on startup with the traceback:

```
Traceback (most recent call last):
  File "col_label.py", line 18, in <module>
    admin = Admin(app, index_view=UserModelView(User, db.session, url='/'))
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/contrib/sqla/view.py", line 291, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/model/base.py", line 587, in __init__
    self._refresh_cache()
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/model/base.py", line 693, in _refresh_cache
    self._refresh_filters_cache()
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/model/base.py", line 622, in _refresh_filters_cache
    if flt.name not in self._filter_groups:
TypeError: unhashable type: '_LazyString'
```
