### ISSUE TITLE
Translated column_labels vs. column_filters

### ISSUE THREAD

**Issue by torotil** [flask-admin/flask-admin#989]
There seems to be a conflict with `lazy_gettext` translated `column_labels`. Here is a minimal example to demonstrate the issue:

```python
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_babelex import lazy_gettext
from flask_sqlalchemy import SQLAlchemy

app = Flask('test')
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String())

class UserModelView(ModelView):
    column_labels = {'name': lazy_gettext('User name')}
    column_filters = ('name', )

admin = Admin(app, index_view=UserModelView(User, db.session, url='/'))

if __name__ == '__main__':
    app.run()
```

The app fails on startup with the traceback:

```
Traceback (most recent call last):
  File "col_label.py", line 18, in <module>
    admin = Admin(app, index_view=UserModelView(User, db.session, url='/'))
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/contrib/sqla/view.py", line 291, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/model/base.py", line 587, in __init__
    self._refresh_cache()
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/model/base.py", line 693, in _refresh_cache
    self._refresh_filters_cache()
  File "/home/roman/.virtualenvs/undok/lib/python3.3/site-packages/Flask_Admin-1.2.0-py3.3.egg/flask_admin/model/base.py", line 622, in _refresh_filters_cache
    if flt.name not in self._filter_groups:
TypeError: unhashable type: '_LazyString'
```

**Comment by litnimax** [comment]
What a syncronizm!
Nearly same ticket at the same time -  #988
:-)

**Comment by torotil** [comment]
Great - so which one do we keep?

**Comment by pawl** [comment]
Closing this one and keeping the first one.
